name: flutter_assignment
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.1
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.5
  flutter_svg: ^2.0.9
  persistent_bottom_nav_bar: ^5.0.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
